call test-affline.webm.bat
call test-afflinefourier.webm.bat
call test-afflineguassian.webm.bat
call test-afflinepyramid.webm.bat
call test-perspective.webm.bat
call test-perspectivefourier.webm.bat
call test-perspectiveguassian.webm.bat
call test-perspectivepyramid.webm.bat
call test-similarity.webm.bat
call test-similarityfourier.webm.bat
call test-similarityguassian.webm.bat
call test-similaritypyramid.webm.bat
