call test-affline.flv.bat
call test-afflinefourier.flv.bat
call test-afflineguassian.flv.bat
call test-afflinepyramid.flv.bat
call test-perspective.flv.bat
call test-perspectivefourier.flv.bat
call test-perspectiveguassian.flv.bat
call test-perspectivepyramid.flv.bat
call test-similarity.flv.bat
call test-similarityfourier.flv.bat
call test-similarityguassian.flv.bat
call test-similaritypyramid.flv.bat
