call test-affline.mp4.bat
call test-afflinefourier.mp4.bat
call test-afflineguassian.mp4.bat
call test-perspective.mp4.bat
call test-perspectivefourier.mp4.bat
call test-perspectiveguassian.mp4.bat
call test-similarity.mp4.bat
call test-similarityfourier.mp4.bat
call test-similarityguassian.mp4.bat
